# Generated by Django 5.2.17 on 2026-08-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=64)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_no', models.CharField(max_length=64, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_storage', 'In Storage'), ('withdrawn', 'Withdrawn'), ('transferred', 'Transferred'), ('adjusted', 'Adjusted')], default='in_storage', max_length=16)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='stock.batch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.customer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='warehouse.location')),
            ],
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('acceptance', 'Acceptance'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment')], max_length=16)),
                ('document_no', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='warehouse.location')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='stock.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
