# Generated by Django 5.2.17 on 2026-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, help_text='Snapshot timestamp auto-captured at the moment a Checker/Operator confirms a scan update.', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='qty_per_layer',
            field=models.PositiveIntegerField(blank=True, help_text='Stock layering: units per layer. Captured once by the Checker on first scan, editable afterwards.', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='uom',
            field=models.CharField(default='box', help_text='Unit of measure, e.g. box, sack, carton.', max_length=20),
        ),
    ]
