# Generated by Django 5.2.17 on 2026-08-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveSmallIntegerField(unique=True)),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('dry', 'Dry'), ('frozen', 'Frozen/Anti'), ('chilled', 'Chilled')], default='frozen', max_length=20)),
                ('capacity_locations', models.PositiveIntegerField(default=0)),
                ('target_temp_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('columns_left', models.PositiveSmallIntegerField(default=15)),
                ('columns_right', models.PositiveSmallIntegerField(default=15)),
                ('levels', models.PositiveSmallIntegerField(default=7)),
                ('depth', models.PositiveSmallIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('column', models.PositiveSmallIntegerField()),
                ('level', models.PositiveSmallIntegerField()),
                ('depth', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('blocked', 'Blocked')], default='empty', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouse.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'status'], name='warehouse_l_room_id_4cf765_idx')],
                'unique_together': {('room', 'side', 'column', 'level', 'depth')},
            },
        ),
    ]
