# Generated by Django 5.2.17 on 2026-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dock_number',
            field=models.CharField(blank=True, help_text='Staging dock this location is nearest to, shown to the Checker on scan.', max_length=20),
        ),
    ]
