# Generated by Django 5.2.17 on 2026-08-12 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_location_dock_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dock_code", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("active", "Active"),
                            ("reserved", "Reserved"),
                            ("offline", "Offline"),
                        ],
                        default="available",
                        max_length=16,
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("loading", "Loading"),
                            ("unloading", "Unloading"),
                        ],
                        default="idle",
                        max_length=16,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Truck plate / carrier / booking reference currently assigned.",
                        max_length=100,
                    ),
                ),
                (
                    "activity_started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the current loading/unloading activity began — used to compute elapsed duration.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["dock_code"],
            },
        ),
        migrations.AddField(
            model_name="room",
            name="floor",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                blank=True,
                help_text="Official FROST room code, e.g. RM101. Backs the rack-level Digital Twin room.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("operational", "Operational"),
                    ("warning", "Warning"),
                    ("maintenance", "Maintenance"),
                    ("offline", "Offline"),
                ],
                default="operational",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="WarehouseArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_code",
                    models.CharField(
                        help_text="Official FROST room code, e.g. RM101, BF101, CHR101, AR101, DWH301.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("area_name", models.CharField(max_length=150)),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("cold_storage", "Cold Storage"),
                            ("blast_freezer", "Blast Freezer"),
                            ("anteroom", "Anteroom"),
                            ("chiller_room", "Chiller Room"),
                            ("dry_warehouse", "Dry Warehouse"),
                        ],
                        max_length=20,
                    ),
                ),
                ("floor", models.CharField(blank=True, max_length=20)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("occupied", models.PositiveIntegerField(default=0)),
                (
                    "target_temp_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("warning", "Warning"),
                            ("maintenance", "Maintenance"),
                            ("offline", "Offline"),
                        ],
                        default="operational",
                        max_length=16,
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked rack-level Room, for Cold Storage areas backed by the Digital Twin.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_area",
                        to="warehouse.room",
                    ),
                ),
            ],
            options={
                "ordering": ["area_type", "area_code"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_code", models.CharField(max_length=20, unique=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("forklift", "Forklift"),
                            ("pallet", "Pallet"),
                            ("stacker", "Stacker"),
                            ("motorized_pallet_truck", "Motorized Pallet Truck"),
                            ("battery", "Battery"),
                            ("dock_leveler", "Dock Leveler"),
                            ("weigh_scale", "Weigh Scale"),
                            ("battery_solution", "Battery Solution"),
                            ("other", "Other Equipment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("in_use", "In Use"),
                            ("maintenance", "Maintenance"),
                            ("retired", "Retired"),
                        ],
                        default="available",
                        max_length=16,
                    ),
                ),
                ("maintenance_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="warehouse.warehousearea",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_type", "asset_code"],
            },
        ),
    ]
